### ISSUE TITLE
parmesan_render_ui function has to take into account  children parameters (showing and hidding them depending on their parent value)

### ISSUE THREAD

**Issue by brazadas** [datasketch/parmesan#10]

**Comment by jpmarindiaz** [comment]
Working on this today. YAML file structure will change

**Comment by brazadas** [comment]
Eso ya lo teníamos en concordancia con como se renderizan hoy en día los parámetros -es decir con la función parmesan_render_ui- (los parámetros hijos se renderizan dentro un div con id que empieza con shn...y de esta manera se pueden apuntar para esconderlos o no dependiendo de el input value del parent) ¿Te mando el código para que lo mires y modifiques si es el caso?

**Comment by jpmarindiaz** [comment]
This funcionality has been rewritten. See the following example app:
`inst/examples/ex04`
