### ISSUE TITLE
double dependence in childs

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/parmesan#13]
for example 'order' depend of ftype and choices are the data categories 
![imagen](https://user-images.githubusercontent.com/17035597/75704338-2f2c6380-5c87-11ea-841a-665f1f016355.png)

**Comment by jpmarindiaz** [comment]
dependency values nos can take any reactive as input
See example 
inst/examples/ex04

![image](https://user-images.githubusercontent.com/1489570/75716214-be904180-5c9c-11ea-8044-6a846aa807b9.png)
