### ISSUE TITLE
Allow any logical statement for the condition that determines the existance of dependent parameters

### ISSUE THREAD

**Issue by brazadas** [datasketch/parmesan#27]
Now you can use  _equals_ but there are situations out of it's scope:
a parameter _F_ that depends on a slider; if the slider value is less than one, _F_ exists, is shown, if not then it is not shown.

**Comment by jpmarindiaz** [comment]
Please list all possible use cases that you can think of. So to better organize the code to cover all cases

**Comment by brazadas** [comment]
I was thinking that maybe there is a workaround; make it depend on a reactive: 
the reactive has _any_ logical statement and the existance of the parameter depends on this reactive

is it possible? if yes, maybe this is easier  than trying to "contemplate" all the possible cases?

**Comment by jpmarindiaz** [comment]
You could indeed work around it. But it would be better for other users to create apps writing only yamls files so they don't have to think about any reactives. We can take care of that. The more examples or use cases the better, with this info we can see which ones make sense to abstract out

**Comment by jpmarindiaz** [comment]
Some examples:

`show_if_all`,`show_if_any` for multiple conditions
`equals` for numbers, booleans, strings
`not_equals`
`is_any_of`
`is_none_of`
`contains` for strings
`does_not_contain`
`in`, `not_in` for vectors
`in_range` for numbers `[1,2]`
`is_between`
`less_than` 
`is_empty`
`is_not_empty`
`is_within` for dates
`is_before`
`is_after`

**Comment by jpmarindiaz** [comment]
See example 06 to see how it works now

https://github.com/datasketch/parmesan/tree/master/inst/examples/ex06-conditions
