### ISSUE TITLE
Make parmesan output work with other environments

### ISSUE THREAD

**Issue by lenafm** [datasketch/parmesan#60]
Make parmesan work with other environment but the current one.

E.g. get `parmesan_output` to work within a function inside the server function of a shiny app.

**Comment by jpmarindiaz** [comment]
I ran out of ideas, I am not particularly savvy with environments. I tried a bunch of combinations of `parent.frame`, `parent.env` and couldn't make it work. This is why there are a bunch of comments in the code of env stuff
